[project]
name = "action-repo"
version = "0.1.1"
description = "A repository for GitHub Actions"
requires-python = ">=3.13"
dependencies = [
    "environs>=14.2.0",
    "requests>=2.32.4",
    "rsa>=4.9.1",
]
