name: 天翼云电脑保活

on:
  schedule:
    - cron: '*/15 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 'Install dependencies'
        run: uv sync

      - name: 'Run script'
        env:
          CTYUN: ${{secrets.CTYUN}}
          TOKEN: ${{secrets.TOKEN}}
        run: uv run python 189/ctyun.py
